version: "3.9"

services:

#backend API
  smartbrainbackend:
    container_name: backend
    # image: node:lts-bullseye
    build: ./
    command: yarn start
    working_dir: /usr/src/smartbrainbackend
    environment:
      - POSTGRES_URI=postgres://ruona:secret@postgres:5432/smartbrain   
      - REDIS_URI=redis://redis:6379

    links:
      - postgres
      - redis
    ports:
      - "5000:5000" 
    volumes:
      - ./:/usr/src/smartbrainbackend

  #postgres
  postgres:
    environment:
      - POSTGRES_USER=ruona
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=smartbrain
      - POSTGRES_HOST=postgres
    build: ./postgres
    ports:
      - "5432:5432"

  #Redis
  redis:
    image: redis
    ports: 
      - "6379:6379"
        
